// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycmxqogbllrwgxrfosml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljbXhxb2dibGxyd2d4cmZvc21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTEyNjMsImV4cCI6MjA2NTgyNzI2M30.pCk3oxaL0btsifFOFBx3FesCHU06yME8JGfQ6c10214";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);